In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [5]:
df = pd.read_csv("C:/Users/hp/Downloads/smartphone_dataset_1M.csv")
print(df)
df.head()

           brand     model_name       os  price_inr  launch_year  5g_support  \
0         Google    Google_2528  Android      71511         2020           1
1        Samsung   Samsung_9006  Android      57511         2018           1
2         Google    Google_2059  Android      76042         2022           0
3         Realme    Realme_5737  Android      26916         2021           0
4        OnePlus   OnePlus_5548  Android      31505         2022           1
...          ...            ...      ...        ...          ...         ...
999995    Google    Google_9242  Android      58041         2025           1
999996   OnePlus   OnePlus_7868  Android      44557         2018           1
999997    Xiaomi    Xiaomi_8446  Android       5000         2021           0
999998  Motorola  Motorola_5474  Android      16253         2023           0
999999    Xiaomi    Xiaomi_5680  Android      15041         2023           1

        dual_sim  expandable_storage  water_resistance  wireless_charging  \
0              1                   0                 0                  1
1              0                   1                 0                  0
2              1                   1                 1                  0
3              1                   0                 1                  0
4              0                   0                 0                  1
...          ...                 ...               ...                ...
999995         0                   0                 0                  0
999996         0                   1                 1                  0
999997         1                   1                 0                  0
999998         1                   1                 0                  1
999999         1                   0                 1                  0

        ...  display_size_inch  display_type  refresh_rate_hz  battery_mah  \
0       ...               6.10        AMOLED              120         4657
1       ...               5.77           LCD              120         3817
2       ...               6.10           LCD               90         5069
3       ...               6.28        AMOLED               60         4323
4       ...               6.45        AMOLED               60         6497
...     ...                ...           ...              ...          ...
999995  ...               6.02          OLED              120         5796
999996  ...               5.97        AMOLED               60         5293
999997  ...               6.42           LCD               60         5326
999998  ...               6.28           LCD               90         5274
999999  ...               6.01        AMOLED               60         5571

        fast_charging_w rear_camera_mp  front_camera_mp  \
0                    25            200               16
1                    65             50                8
2                    25            200               32
3                    45             50                8
4                    25             50               16
...                 ...            ...              ...
999995               45             50               32
999996              100            108               50
999997               18             50               16
999998               25             50               16
999999               25             48               32

                         camera_setup  weight_g thickness_mm
0                                Wide     175.2         8.29
1                     Telephoto, Wide     175.6         7.41
2                    Wide, Ultra-Wide     184.0         8.89
3       Macro, Wide, Telephoto, Depth     173.6         7.67
4       Depth, Macro, Telephoto, Wide     197.9         9.41
...                               ...       ...          ...
999995                    Depth, Wide     180.8         7.11
999996    Telephoto, Wide, Ultra-Wide     204.1         8.54
999997             Depth, Macro, Wide     158.1         8.68
999998       Macro, Ultra-Wide, Depth     197.6         8.97
999999       Ultra-Wide, Macro, Depth     186.2         8.55

[1000000 rows x 33 columns]

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,...,display_size_inch,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g,thickness_mm
0,Google,Google_2528,Android,71511,2020,1,1,0,0,1,...,6.10,AMOLED,120,4657,25,200,16,Wide,175.2,8.29
1,Samsung,Samsung_9006,Android,57511,2018,1,0,1,0,0,...,5.77,LCD,120,3817,65,50,8,"Telephoto, Wide",175.6,7.41
2,Google,Google_2059,Android,76042,2022,0,1,1,1,0,...,6.10,LCD,90,5069,25,200,32,"Wide, Ultra-Wide",184.0,8.89
3,Realme,Realme_5737,Android,26916,2021,0,1,0,1,0,...,6.28,AMOLED,60,4323,45,50,8,"Macro, Wide, Telephoto, Depth",173.6,7.67
4,OnePlus,OnePlus_5548,Android,31505,2022,1,0,0,0,1,...,6.45,AMOLED,60,6497,25,50,16,"Depth, Macro, Telephoto, Wide",197.9,9.41

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 33 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   brand                 1000000 non-null  object
 1   model_name            1000000 non-null  object
 2   os                    1000000 non-null  object
 3   price_inr             1000000 non-null  int64
 4   launch_year           1000000 non-null  int64
 5   5g_support            1000000 non-null  int64
 6   dual_sim              1000000 non-null  int64
 7   expandable_storage    1000000 non-null  int64
 8   water_resistance      1000000 non-null  int64
 9   wireless_charging     1000000 non-null  int64
 10  fingerprint_sensor    1000000 non-null  int64
 11  face_unlock           1000000 non-null  int64
 12  gpu_score             1000000 non-null  int64
 13  cpu_score             1000000 non-null  int64
 14  screen_to_body_ratio  1000000 non-null  float64
 15  build_material        1000000 non-null  object
 16  colors_available      1000000 non-null  int64
 17  warranty_years        1000000 non-null  int64
 18  bluetooth_version     1000000 non-null  float64
 19  wifi_version          1000000 non-null  object
 20  chipset               1000000 non-null  object
 21  ram_gb                1000000 non-null  int64
 22  storage_gb            1000000 non-null  int64
 23  display_size_inch     1000000 non-null  float64
 24  display_type          1000000 non-null  object
 25  refresh_rate_hz       1000000 non-null  int64
 26  battery_mah           1000000 non-null  int64
 27  fast_charging_w       1000000 non-null  int64
 28  rear_camera_mp        1000000 non-null  int64
 29  front_camera_mp       1000000 non-null  int64
 30  camera_setup          1000000 non-null  object
 31  weight_g              1000000 non-null  float64
 32  thickness_mm          1000000 non-null  float64
dtypes: float64(5), int64(20), object(8)
memory usage: 251.8+ MB

In [7]:
df.size

33000000

In [8]:
df.shape

(1000000, 33)

In [9]:
df.describe

<bound method NDFrame.describe of            brand     model_name       os  price_inr  launch_year  5g_support  \
0         Google    Google_2528  Android      71511         2020           1
1        Samsung   Samsung_9006  Android      57511         2018           1
2         Google    Google_2059  Android      76042         2022           0
3         Realme    Realme_5737  Android      26916         2021           0
4        OnePlus   OnePlus_5548  Android      31505         2022           1
...          ...            ...      ...        ...          ...         ...
999995    Google    Google_9242  Android      58041         2025           1
999996   OnePlus   OnePlus_7868  Android      44557         2018           1
999997    Xiaomi    Xiaomi_8446  Android       5000         2021           0
999998  Motorola  Motorola_5474  Android      16253         2023           0
999999    Xiaomi    Xiaomi_5680  Android      15041         2023           1

        dual_sim  expandable_storage  water_resistance  wireless_charging  \
0              1                   0                 0                  1
1              0                   1                 0                  0
2              1                   1                 1                  0
3              1                   0                 1                  0
4              0                   0                 0                  1
...          ...                 ...               ...                ...
999995         0                   0                 0                  0
999996         0                   1                 1                  0
999997         1                   1                 0                  0
999998         1                   1                 0                  1
999999         1                   0                 1                  0

        ...  display_size_inch  display_type  refresh_rate_hz  battery_mah  \
0       ...               6.10        AMOLED              120         4657
1       ...               5.77           LCD              120         3817
2       ...               6.10           LCD               90         5069
3       ...               6.28        AMOLED               60         4323
4       ...               6.45        AMOLED               60         6497
...     ...                ...           ...              ...          ...
999995  ...               6.02          OLED              120         5796
999996  ...               5.97        AMOLED               60         5293
999997  ...               6.42           LCD               60         5326
999998  ...               6.28           LCD               90         5274
999999  ...               6.01        AMOLED               60         5571

        fast_charging_w rear_camera_mp  front_camera_mp  \
0                    25            200               16
1                    65             50                8
2                    25            200               32
3                    45             50                8
4                    25             50               16
...                 ...            ...              ...
999995               45             50               32
999996              100            108               50
999997               18             50               16
999998               25             50               16
999999               25             48               32

                         camera_setup  weight_g thickness_mm
0                                Wide     175.2         8.29
1                     Telephoto, Wide     175.6         7.41
2                    Wide, Ultra-Wide     184.0         8.89
3       Macro, Wide, Telephoto, Depth     173.6         7.67
4       Depth, Macro, Telephoto, Wide     197.9         9.41
...                               ...       ...          ...
999995                    Depth, Wide     180.8         7.11
999996    Telephoto, Wide, Ultra-Wide     204.1         8.54
999997             Depth, Macro, Wide     158.1         8.68
999998       Macro, Ultra-Wide, Depth     197.6         8.97
999999       Ultra-Wide, Macro, Depth     186.2         8.55

[1000000 rows x 33 columns]>

In [10]:
for i in df.columns:
    print(df[i].unique())

['Google' 'Samsung' 'Realme' 'OnePlus' 'Vivo' 'Nothing' 'Apple' 'Oppo'
 'Motorola' 'Xiaomi']
['Google_2528' 'Samsung_9006' 'Google_2059' ... 'Nothing_9484'
 'Nothing_6609' 'Vivo_3480']
['Android' 'iOS']
[ 71511  57511  76042 ... 104062 113988  71971]
[2020 2018 2022 2021 2025 2019 2023 2024]
[1 0]
[1 0]
[0 1]
[0 1]
[1 0]
[1 0]
[1 0]
[ 6850  6100  6862 ... 12588 12675  -726]
[ 8793  7275  9390 ... 15166 -1473 15424]
[88.68 88.02 83.33 ... 91.59 91.92 79.07]
['Metal' 'Glass' 'Plastic']
[5 2 4 6 3 7]
[1 2]
[5.2 5.  5.3 5.1 4.2]
['WiFi 5' 'WiFi 6' 'WiFi 6E']
['Tensor G3' 'A17 Bionic' 'Snapdragon 8 Gen 2' 'Dimensity 900'
 'Exynos 1380' 'Snapdragon 778G' 'Helio G85' 'Snapdragon 680'
 'Dimensity 6020']
[12 16  8  6  4  3]
[128  64 256 512]
[6.1  5.77 6.28 6.45 5.85 6.23 5.95 6.2  6.08 6.49 5.52 6.03 6.37 6.25
 5.67 6.66 6.65 5.97 6.06 6.82 6.24 5.88 5.56 6.89 6.22 6.46 5.53 6.85
 5.6  6.18 6.32 6.74 6.76 6.84 6.47 5.64 6.01 6.67 5.66 6.33 6.51 5.92
 6.87 6.62 5.51 6.55 6.31 6.07 6.5  6.43 5.62 6.27 6.16 6.05 5.55 5.87
 5.76 6.12 6.26 6.75 5.82 6.42 6.58 6.71 6.69 6.3  6.79 5.68 6.88 6.17
 5.89 6.44 5.78 6.6  5.84 5.69 6.73 5.91 6.13 6.61 5.99 5.98 5.58 6.36
 6.8  5.9  6.35 5.94 6.15 5.57 5.63 5.93 6.53 5.86 5.79 6.72 6.   5.59
 6.57 6.63 6.81 5.96 6.56 6.54 6.02 5.8  5.54 6.59 6.52 5.5  6.38 6.39
 6.83 6.78 5.74 6.04 5.83 5.81 6.68 5.65 5.72 6.4  5.73 6.77 6.11 6.29
 6.7  6.48 6.21 6.86 6.64 5.75 5.7  6.41 6.14 6.19 5.71 6.09 5.61 6.9
 6.34]
['AMOLED' 'LCD' 'OLED']
[120  90  60 144]
[4657 3817 5069 ... 2213 8170 2345]
[ 25  65  45  33  18 100]
[200  50  64 108  13  48]
[16  8 32 50]
['Wide' 'Telephoto, Wide' 'Wide, Ultra-Wide'
 'Macro, Wide, Telephoto, Depth' 'Depth, Macro, Telephoto, Wide'
 'Ultra-Wide, Wide, Macro' 'Depth, Macro, Telephoto'
 'Ultra-Wide, Macro, Wide' 'Ultra-Wide' 'Macro, Telephoto, Depth'
 'Depth, Telephoto, Macro' 'Wide, Ultra-Wide, Depth' 'Depth, Macro'
 'Telephoto, Wide, Macro' 'Wide, Telephoto' 'Telephoto, Ultra-Wide, Macro'
 'Depth, Ultra-Wide' 'Telephoto, Depth' 'Depth' 'Wide, Depth'
 'Macro, Ultra-Wide' 'Ultra-Wide, Depth' 'Wide, Depth, Macro, Telephoto'
 'Ultra-Wide, Wide' 'Wide, Telephoto, Ultra-Wide' 'Wide, Macro, Depth'
 'Macro' 'Ultra-Wide, Macro' 'Telephoto, Depth, Wide' 'Telephoto'
 'Telephoto, Macro, Ultra-Wide, Wide' 'Macro, Depth'
 'Depth, Wide, Ultra-Wide' 'Depth, Ultra-Wide, Wide'
 'Ultra-Wide, Wide, Depth' 'Depth, Macro, Wide' 'Depth, Telephoto'
 'Wide, Macro, Depth, Ultra-Wide' 'Telephoto, Ultra-Wide'
 'Wide, Telephoto, Depth' 'Ultra-Wide, Telephoto'
 'Ultra-Wide, Telephoto, Wide' 'Telephoto, Ultra-Wide, Wide'
 'Depth, Macro, Ultra-Wide' 'Telephoto, Wide, Depth' 'Depth, Wide'
 'Wide, Macro, Ultra-Wide, Telephoto' 'Macro, Telephoto'
 'Telephoto, Ultra-Wide, Depth' 'Macro, Depth, Telephoto, Wide'
 'Macro, Telephoto, Wide' 'Ultra-Wide, Wide, Telephoto'
 'Telephoto, Wide, Macro, Ultra-Wide' 'Telephoto, Macro, Depth'
 'Wide, Depth, Telephoto, Ultra-Wide' 'Wide, Ultra-Wide, Telephoto'
 'Macro, Wide' 'Depth, Wide, Macro' 'Wide, Depth, Ultra-Wide'
 'Depth, Macro, Telephoto, Ultra-Wide' 'Wide, Macro'
 'Macro, Wide, Telephoto' 'Depth, Wide, Telephoto, Ultra-Wide'
 'Telephoto, Macro' 'Wide, Macro, Ultra-Wide' 'Macro, Ultra-Wide, Wide'
 'Ultra-Wide, Macro, Telephoto' 'Macro, Depth, Ultra-Wide'
 'Wide, Depth, Macro' 'Macro, Ultra-Wide, Telephoto, Depth'
 'Ultra-Wide, Telephoto, Depth' 'Ultra-Wide, Telephoto, Macro, Wide'
 'Depth, Wide, Macro, Ultra-Wide' 'Depth, Ultra-Wide, Telephoto'
 'Telephoto, Depth, Macro' 'Depth, Telephoto, Ultra-Wide'
 'Telephoto, Macro, Wide, Depth' 'Ultra-Wide, Telephoto, Wide, Macro'
 'Wide, Depth, Telephoto' 'Wide, Depth, Ultra-Wide, Telephoto'
 'Macro, Wide, Ultra-Wide' 'Ultra-Wide, Depth, Macro'
 'Depth, Wide, Ultra-Wide, Macro' 'Depth, Wide, Macro, Telephoto'
 'Depth, Ultra-Wide, Wide, Telephoto' 'Macro, Depth, Wide'
 'Macro, Depth, Wide, Ultra-Wide' 'Ultra-Wide, Depth, Telephoto'
 'Wide, Ultra-Wide, Macro, Telephoto' 'Ultra-Wide, Depth, Wide'
 'Wide, Telephoto, Depth, Macro' 'Depth, Ultra-Wide, Macro'
 'Macro, Telephoto, Ultra-Wide' 'Macro, Telephoto, Wide, Ultra-Wide'
 'Telephoto, Macro, Depth, Wide' 'Depth, Telephoto, Wide, Ultra-Wide'
 'Telephoto, Macro, Depth, Ultra-Wide' 'Wide, Macro, Telephoto, Depth'
 'Wide, Ultra-Wide, Macro' 'Telephoto, Wide, Ultra-Wide'
 'Depth, Telephoto, Wide' 'Ultra-Wide, Macro, Telephoto, Wide'
 'Wide, Macro, Telephoto' 'Macro, Depth, Telephoto, Ultra-Wide'
 'Depth, Ultra-Wide, Macro, Wide' 'Macro, Ultra-Wide, Telephoto'
 'Depth, Telephoto, Ultra-Wide, Wide' 'Depth, Wide, Telephoto'
 'Ultra-Wide, Telephoto, Depth, Wide' 'Macro, Wide, Depth, Ultra-Wide'
 'Ultra-Wide, Depth, Macro, Telephoto'
 'Macro, Telephoto, Ultra-Wide, Wide' 'Ultra-Wide, Telephoto, Macro'
 'Ultra-Wide, Depth, Macro, Wide' 'Telephoto, Ultra-Wide, Depth, Wide'
 'Macro, Ultra-Wide, Depth' 'Macro, Depth, Telephoto'
 'Depth, Ultra-Wide, Wide, Macro' 'Telephoto, Depth, Ultra-Wide, Wide'
 'Macro, Ultra-Wide, Depth, Telephoto' 'Wide, Telephoto, Macro'
 'Depth, Ultra-Wide, Macro, Telephoto' 'Ultra-Wide, Depth, Wide, Macro'
 'Telephoto, Macro, Wide' 'Ultra-Wide, Telephoto, Macro, Depth'
 'Telephoto, Ultra-Wide, Macro, Wide' 'Macro, Wide, Depth'
 'Telephoto, Depth, Macro, Ultra-Wide'
 'Wide, Telephoto, Macro, Ultra-Wide' 'Telephoto, Depth, Ultra-Wide'
 'Depth, Telephoto, Macro, Wide' 'Telephoto, Macro, Ultra-Wide'
 'Ultra-Wide, Wide, Macro, Depth' 'Depth, Telephoto, Macro, Ultra-Wide'
 'Wide, Ultra-Wide, Telephoto, Depth' 'Ultra-Wide, Depth, Telephoto, Wide'
 'Wide, Depth, Macro, Ultra-Wide' 'Depth, Macro, Wide, Ultra-Wide'
 'Depth, Macro, Wide, Telephoto' 'Macro, Ultra-Wide, Wide, Depth'
 'Depth, Wide, Ultra-Wide, Telephoto' 'Ultra-Wide, Macro, Depth'
 'Wide, Macro, Telephoto, Ultra-Wide' 'Ultra-Wide, Wide, Depth, Macro'
 'Wide, Depth, Telephoto, Macro' 'Telephoto, Depth, Macro, Wide'
 'Ultra-Wide, Macro, Wide, Depth' 'Telephoto, Wide, Ultra-Wide, Macro'
 'Macro, Wide, Depth, Telephoto' 'Depth, Wide, Telephoto, Macro'
 'Macro, Wide, Ultra-Wide, Telephoto' 'Wide, Telephoto, Ultra-Wide, Macro'
 'Macro, Telephoto, Wide, Depth' 'Macro, Depth, Ultra-Wide, Wide'
 'Ultra-Wide, Telephoto, Depth, Macro'
 'Ultra-Wide, Wide, Telephoto, Macro' 'Wide, Macro, Ultra-Wide, Depth'
 'Macro, Ultra-Wide, Wide, Telephoto' 'Depth, Telephoto, Wide, Macro'
 'Ultra-Wide, Wide, Macro, Telephoto' 'Wide, Telephoto, Depth, Ultra-Wide'
 'Ultra-Wide, Macro, Telephoto, Depth'
 'Ultra-Wide, Wide, Telephoto, Depth'
 'Telephoto, Macro, Ultra-Wide, Depth'
 'Ultra-Wide, Macro, Wide, Telephoto'
 'Telephoto, Ultra-Wide, Macro, Depth'
 'Wide, Ultra-Wide, Telephoto, Macro' 'Ultra-Wide, Depth, Wide, Telephoto'
 'Macro, Depth, Ultra-Wide, Telephoto'
 'Telephoto, Wide, Ultra-Wide, Depth' 'Telephoto, Depth, Wide, Ultra-Wide'
 'Telephoto, Wide, Depth, Ultra-Wide' 'Ultra-Wide, Telephoto, Wide, Depth'
 'Telephoto, Macro, Wide, Ultra-Wide'
 'Depth, Ultra-Wide, Telephoto, Macro'
 'Wide, Ultra-Wide, Depth, Telephoto' 'Telephoto, Ultra-Wide, Wide, Depth'
 'Wide, Telephoto, Macro, Depth' 'Macro, Ultra-Wide, Depth, Wide'
 'Telephoto, Ultra-Wide, Wide, Macro' 'Wide, Depth, Ultra-Wide, Macro'
 'Ultra-Wide, Macro, Depth, Telephoto'
 'Telephoto, Ultra-Wide, Depth, Macro' 'Telephoto, Wide, Depth, Macro'
 'Wide, Telephoto, Ultra-Wide, Depth' 'Macro, Telephoto, Depth, Wide'
 'Macro, Telephoto, Depth, Ultra-Wide' 'Ultra-Wide, Macro, Depth, Wide'
 'Depth, Telephoto, Ultra-Wide, Macro' 'Macro, Depth, Wide, Telephoto'
 'Depth, Ultra-Wide, Telephoto, Wide'
 'Depth, Macro, Ultra-Wide, Telephoto'
 'Ultra-Wide, Depth, Telephoto, Macro'
 'Telephoto, Depth, Ultra-Wide, Macro'
 'Macro, Wide, Telephoto, Ultra-Wide' 'Macro, Wide, Ultra-Wide, Depth'
 'Wide, Ultra-Wide, Depth, Macro' 'Macro, Ultra-Wide, Telephoto, Wide'
 'Macro, Telephoto, Ultra-Wide, Depth' 'Depth, Macro, Ultra-Wide, Wide'
 'Telephoto, Wide, Macro, Depth' 'Wide, Ultra-Wide, Macro, Depth'
 'Telephoto, Depth, Wide, Macro' 'Ultra-Wide, Wide, Depth, Telephoto'
 'Wide, Macro, Depth, Telephoto']
[175.2 175.6 184.  ...  99.2 112.6 106.7]
[8.29 7.41 8.89 7.67 9.41 9.16 9.17 8.02 9.03 7.26 8.77 7.42 8.34 8.28
 8.47 8.53 8.78 8.8  8.   8.79 9.19 9.25 7.86 9.31 8.2  9.21 7.17 8.87
 7.15 7.9  8.65 8.52 8.83 9.24 7.05 9.05 8.08 7.89 7.49 8.4  8.99 7.16
 8.07 7.78 8.9  7.66 8.97 7.69 7.03 9.23 7.88 9.43 7.75 7.33 9.28 8.7
 9.44 8.04 8.93 7.84 7.19 8.03 9.18 8.57 8.81 7.1  8.55 9.38 7.53 8.35
 7.93 7.94 9.07 8.46 7.29 8.56 8.63 7.65 8.15 8.25 8.45 7.44 7.55 7.32
 7.45 8.41 7.64 7.52 9.32 7.79 7.46 7.48 7.97 9.34 8.21 7.77 9.49 9.06
 7.61 7.28 9.3  8.36 8.1  8.62 7.09 9.15 8.27 8.67 7.13 7.22 8.13 8.66
 7.02 8.26 7.8  7.96 8.33 8.75 8.84 7.34 9.37 9.48 8.32 7.25 9.09 8.76
 9.13 7.11 8.44 8.05 8.86 8.3  9.01 7.4  7.12 7.51 7.73 8.18 8.54 7.83
 7.43 8.51 7.71 9.27 7.76 8.6  8.96 7.6  9.29 7.23 7.68 9.02 9.12 8.09
 8.11 7.04 8.5  7.72 7.74 9.08 8.61 7.59 8.69 8.72 7.57 9.36 8.19 7.08
 7.21 7.2  9.5  9.1  9.42 7.63 8.64 7.47 8.92 8.48 7.56 7.54 9.26 8.95
 8.85 7.81 7.35 7.07 9.2  8.38 8.01 9.46 7.14 7.99 7.92 7.98 8.73 7.82
 8.31 8.94 8.23 7.62 9.35 7.3  7.24 7.27 8.37 7.38 8.91 8.71 8.49 8.06
 7.37 9.14 9.47 7.87 9.33 9.04 7.18 8.58 7.91 7.7  7.5  8.24 8.59 8.22
 8.16 7.06 8.17 9.22 8.43 8.82 8.88 8.42 7.01 8.74 7.85 9.45 7.   7.58
 7.39 8.98 7.31 8.12 7.36 9.4  7.95 9.   9.11 8.68 8.39 8.14 9.39]

In [11]:
for i in df.columns:
    print(df[i].nunique())

10
89990
2
108967
8
2
2
2
2
2
2
2
14109
17040
2001
3
6
2
5
3
9
6
4
141
3
4
5809
6
6
4
205
1607
251

In [12]:
print("Before duplicates:",df.shape)
df = df.drop_duplicates()
print("After duplicates:",df.shape)

Before duplicates: (1000000, 33)
After duplicates: (1000000, 33)

In [13]:
Q1 = df['price_inr'].quantile(0.25)
Q3 = df['price_inr'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df = df[(df['price_inr'] >= lower) & (df['price_inr'] <= upper)]

print(df.shape)

(969225, 33)

In [14]:
if 'model_name' in df.columns:
    df.drop('model_name', axis=1, inplace=True)

In [15]:
df.head()

,brand,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,fingerprint_sensor,...,display_size_inch,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g,thickness_mm
0,Google,Android,71511,2020,1,1,0,0,1,1,...,6.10,AMOLED,120,4657,25,200,16,Wide,175.2,8.29
1,Samsung,Android,57511,2018,1,0,1,0,0,1,...,5.77,LCD,120,3817,65,50,8,"Telephoto, Wide",175.6,7.41
2,Google,Android,76042,2022,0,1,1,1,0,1,...,6.10,LCD,90,5069,25,200,32,"Wide, Ultra-Wide",184.0,8.89
3,Realme,Android,26916,2021,0,1,0,1,0,1,...,6.28,AMOLED,60,4323,45,50,8,"Macro, Wide, Telephoto, Depth",173.6,7.67
4,OnePlus,Android,31505,2022,1,0,0,0,1,1,...,6.45,AMOLED,60,6497,25,50,16,"Depth, Macro, Telephoto, Wide",197.9,9.41

In [16]:
X = df.drop('price_inr', axis=1)
y = df['price_inr']

In [17]:
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

print(numeric_features)
print(categorical_features)

Index(['launch_year', '5g_support', 'dual_sim', 'expandable_storage',
       'water_resistance', 'wireless_charging', 'fingerprint_sensor',
       'face_unlock', 'gpu_score', 'cpu_score', 'screen_to_body_ratio',
       'colors_available', 'warranty_years', 'bluetooth_version', 'ram_gb',
       'storage_gb', 'display_size_inch', 'refresh_rate_hz', 'battery_mah',
       'fast_charging_w', 'rear_camera_mp', 'front_camera_mp', 'weight_g',
       'thickness_mm'],
      dtype='object')
Index(['brand', 'os', 'build_material', 'wifi_version', 'chipset',
       'display_type', 'camera_setup'],
      dtype='object')

In [18]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [19]:
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
from xgboost import XGBRegressor

In [24]:
model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=10,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

In [25]:
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model)
])

In [26]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['launch_year', '5g_support', 'dual_sim', 'expandable_storage',
       'water_resistance', 'wireless_charging', 'fingerprint_sensor',
       'face_unlock', 'gpu_score', 'cpu_score', 'screen_to_body_ratio',
       '...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=10, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [27]:
y_pred = pipeline.predict(X_test)

In [29]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [30]:
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R2 Score:", r2)
print("MAE:", mae)
print("RMSE:", rmse)

R2 Score: 0.9852563142776489
MAE: 2117.157470703125
RMSE: 2678.9192783658114

In [31]:
model = pipeline.named_steps['model']

importance = model.feature_importances_

print(importance)

[4.80260642e-05 4.73963701e-05 5.79701555e-05 5.41454792e-05
 5.72310928e-05 6.09308008e-05 7.35863214e-05 6.68111315e-05
 4.87034582e-02 6.64236188e-01 1.13933987e-04 9.52102637e-05
 8.87242641e-05 9.72275739e-05 1.77996848e-02 9.64393912e-05
 1.20890661e-04 1.46435239e-04 1.28221742e-04 1.03479200e-04
 1.17581934e-02 1.01933394e-04 1.28177824e-04 1.29113047e-04
 1.15562089e-01 1.93652026e-02 1.19129440e-03 3.34449625e-03
 4.41575423e-03 8.52944446e-04 1.47306477e-03 1.21357301e-02
 1.08638196e-03 1.07563590e-03 2.07709009e-03 2.44627387e-04
 1.06275009e-04 1.06434709e-04 1.09072018e-04 1.08527267e-04
 1.04709572e-04 1.05208484e-04 7.10997125e-03 7.58322747e-03
 8.14205781e-03 6.90477993e-03 5.61269745e-03 5.45735145e-03
 6.23019645e-03 9.17093735e-03 7.19744293e-03 1.06528183e-04
 2.04591604e-04 1.12704547e-04 1.45449885e-04 1.48720937e-04
 1.35042763e-04 1.43232130e-04 1.22255165e-04 1.45527505e-04
 1.29235865e-04 1.35097158e-04 1.45524755e-04 1.30778571e-04
 1.38401971e-04 1.47178609e-04 1.40759323e-04 1.66209880e-04
 1.13868067e-04 1.55444053e-04 1.45666432e-04 1.39187701e-04
 1.50634049e-04 1.29772205e-04 1.34960632e-04 1.44538542e-04
 1.52374385e-04 1.41653902e-04 1.36822200e-04 1.61946766e-04
 1.24868908e-04 1.32000059e-04 1.43893296e-04 1.24470826e-04
 1.30664645e-04 1.42378107e-04 1.47951068e-04 1.23612495e-04
 1.32590096e-04 1.58899566e-04 1.32880727e-04 1.28854459e-04
 1.63746750e-04 1.41181372e-04 1.37254363e-04 1.45202037e-04
 1.53821733e-04 1.43712154e-04 1.28969463e-04 1.31322668e-04
 1.39534095e-04 1.20196361e-04 1.29704320e-04 1.53100860e-04
 1.20557001e-04 1.39667041e-04 1.60925716e-04 1.32201851e-04
 1.32593443e-04 1.30626839e-04 1.49647865e-04 1.24615821e-04
 1.18693169e-04 1.54047593e-04 1.42911420e-04 1.36442395e-04
 1.53213099e-04 1.48497478e-04 1.38070362e-04 1.54875830e-04
 1.46737919e-04 1.43711062e-04 1.42443838e-04 1.46961698e-04
 1.44921709e-04 1.59612187e-04 1.45972721e-04 1.38701624e-04
 1.38451913e-04 1.22180223e-04 1.53370318e-04 1.31781693e-04
 1.35496739e-04 1.39326032e-04 1.31260138e-04 1.28620653e-04
 1.49375264e-04 1.49707659e-04 1.36457777e-04 1.32142042e-04
 1.06358180e-04 1.54803478e-04 1.27227322e-04 1.32815112e-04
 1.41291064e-04 1.36459654e-04 1.21564117e-04 1.46446473e-04
 1.49526270e-04 1.22276309e-04 1.07676824e-04 1.49849555e-04
 1.26193860e-04 1.29106615e-04 1.49662228e-04 1.43187193e-04
 1.18658638e-04 1.54874171e-04 1.42812933e-04 1.33510999e-04
 1.35072551e-04 1.53036759e-04 1.18127151e-04 1.20723969e-04
 1.52936453e-04 1.22701735e-04 1.31320048e-04 1.48509993e-04
 1.49138097e-04 1.46097882e-04 1.32649599e-04 1.48668041e-04
 1.21407975e-04 1.43924612e-04 1.50943190e-04 1.36785820e-04
 1.25884384e-04 1.35673414e-04 1.60157346e-04 1.52578243e-04
 1.37045310e-04 1.33348702e-04 1.39798256e-04 1.38959585e-04
 1.25217906e-04 1.47007580e-04 1.29146283e-04 1.28378641e-04
 1.43108540e-04 1.45461308e-04 1.03574108e-04 1.38936331e-04
 1.41179262e-04 1.39568510e-04 1.27554318e-04 1.59886185e-04
 1.24562284e-04 1.34027418e-04 1.51044209e-04 1.54636931e-04
 1.26657746e-04 1.07977372e-04 1.36804054e-04 1.40653094e-04
 1.28006432e-04 1.63427714e-04 1.33187932e-04 1.26628438e-04
 1.43554309e-04 1.54748413e-04 1.43290847e-04 1.33931564e-04
 1.52986715e-04 1.18643758e-04 1.32287489e-04 1.48307619e-04
 1.28948770e-04 1.17319207e-04 1.45879691e-04 1.54081150e-04
 1.51069078e-04 1.41103679e-04 1.42802033e-04 1.48417399e-04
 1.31199879e-04 1.24164464e-04 1.56698385e-04 1.16218063e-04
 1.30458226e-04 1.45936676e-04 1.49620580e-04 1.29619963e-04
 1.36745817e-04 1.52419874e-04 1.24001876e-04 1.23814869e-04
 1.46212347e-04 1.26824714e-04 1.49383981e-04 1.49817279e-04
 1.53522225e-04 1.33457230e-04 1.13486982e-04 1.39836498e-04
 1.29103661e-04 1.24439073e-04 1.48966836e-04 1.20236400e-04
 1.40994220e-04 1.38233634e-04 1.63496356e-04 1.14522540e-04
 1.29502034e-04 1.59653922e-04 1.40402262e-04 1.47293656e-04
 1.48115345e-04 1.33216599e-04 1.28342333e-04]

In [32]:
import pickle

pickle.dump(pipeline, open('smartphone_price_model.pkl', 'wb'))

In [33]:
loaded_model = pickle.load(open('smartphone_price_model.pkl', 'rb'))

In [34]:
import gradio as gr
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import r2_score
from xgboost import XGBRegressor
df = pd.read_csv("C:/Users/hp/Downloads/smartphone_dataset_1M.csv")
df = df.drop_duplicates()
Q1 = df['price_inr'].quantile(0.25)
Q3 = df['price_inr'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[
    (df['price_inr'] >= lower) &
    (df['price_inr'] <= upper)
]
if 'model_name' in df.columns:
    df.drop('model_name', axis=1, inplace=True)
X = df.drop('price_inr', axis=1)
y = df['price_inr']
numeric_features = X.select_dtypes(
    include=['int64', 'float64']
).columns

categorical_features = X.select_dtypes(
    include=['object']
).columns
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=10,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model)
])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

score = r2_score(y_test, y_pred)

print("R2 Score:", score)

pickle.dump(pipeline, open("smartphone_price_model.pkl", "wb"))


def predict_price(*inputs):

    input_data = pd.DataFrame([inputs], columns=X.columns)

    prediction = pipeline.predict(input_data)[0]

    return f"Predicted Smartphone Price: ₹ {round(prediction, 2)}"


inputs = []

for col in X.columns:

    if col in numeric_features:

        inputs.append(
            gr.Number(label=col)
        )

    else:

        choices = list(df[col].dropna().unique())

        inputs.append(
            gr.Dropdown(
                choices=choices,
                label=col
            )
        )

interface = gr.Interface(
    fn=predict_price,
    inputs=inputs,
    outputs=gr.Textbox(),
    title="Smartphone Price Prediction",
    description="Predict smartphone prices using Machine Learning"
)

interface.launch()

R2 Score: 0.9852563142776489
* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.